"""initial migration

Revision ID: 501ece629d80
Revises: 
Create Date: 2025-11-21 15:06:28.981531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501ece629d80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
