"""add movimentacoes_saida

Revision ID: 6fc89adfaba0
Revises: fbe863b5af80
Create Date: 2026-04-03 11:19:43.753441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc89adfaba0'
down_revision = 'fbe863b5af80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lucro_real', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estornada', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_saida')
    # ### end Alembic commands ###
