"""add lucro_real na pagina do histórico

Revision ID: a47633d4ad48
Revises: b6aa1c3490fc
Create Date: 2025-12-12 16:36:24.030603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47633d4ad48'
down_revision = 'b6aa1c3490fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_fiscal', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_column('nota_fiscal')

    # ### end Alembic commands ###
