"""add lote and lucro_real

Revision ID: b6aa1c3490fc
Revises: d9115e9a14d2
Create Date: 2025-12-12 11:55:23.285072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6aa1c3490fc'
down_revision = 'd9115e9a14d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('data_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lucro_real', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_column('lucro_real')

    op.drop_table('lotes')
    # ### end Alembic commands ###
