"""create despesas_mensais table

Revision ID: d9115e9a14d2
Revises: ff1baf5ea4f5
Create Date: 2025-12-06 18:35:04.309906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9115e9a14d2'
down_revision = 'ff1baf5ea4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_despesa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas_mensais')
    # ### end Alembic commands ###
