"""add itens_movimentacao_saida

Revision ID: db17cf702981
Revises: 6fc89adfaba0
Create Date: 2026-04-04 08:38:07.975227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db17cf702981'
down_revision = '6fc89adfaba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_movimentacao_saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimentacao_saida_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['movimentacao_saida_id'], ['movimentacoes_saida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_movimentacao_saida')
    # ### end Alembic commands ###
