"""add tipo to pruduto

Revision ID: fbe863b5af80
Revises: 48c75dc6b7bc
Create Date: 2026-01-01 22:16:57.545076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe863b5af80'
down_revision = '48c75dc6b7bc'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tipo',
                sa.String(length=20),
                nullable=False,
                server_default='madeira'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
